'use client';

import {
  AlertCircle,
  Check,
  ChevronDown,
  Code,
  Copy,
  Download,
  ExternalLink,
  FileCode,
  Globe,
  Layers,
  Loader2,
  Monitor,
  MousePointer,
  RefreshCw,
  Settings,
  Smartphone,
  Tablet,
  Zap,
} from 'lucide-react';
import { useCallback, useState } from 'react';

// Types
type ExportPreset = 'basic' | 'interactive' | 'responsive' | 'prototype';
type DevicePreview = 'desktop' | 'tablet' | 'mobile';

type InteractivityOption = {
  id: string;
  label: string;
  description: string;
  enabled: boolean;
  icon: typeof MousePointer;
};

type HTMLExportSettings = {
  preset: ExportPreset;
  includeCSS: boolean;
  inlineStyles: boolean;
  minify: boolean;
  responsive: boolean;
  darkModeSupport: boolean;
  clickableElements: boolean;
  hoverEffects: boolean;
  animations: boolean;
  customCSS?: string;
  exportAsZip: boolean;
};

type InteractiveHTMLExportProps = {
  variant?: 'full' | 'compact' | 'widget';
  mockupId?: string;
  mockupName?: string;
  onExport?: (settings: HTMLExportSettings) => void;
  onPreview?: (device: DevicePreview) => void;
  className?: string;
};

// Preset configurations
const presetConfig = {
  basic: {
    label: 'Basic HTML',
    description: 'Clean HTML with embedded styles',
    icon: FileCode,
    features: ['Semantic HTML', 'Embedded CSS', 'Static content'],
  },
  interactive: {
    label: 'Interactive',
    description: 'Clickable elements with hover states',
    icon: MousePointer,
    features: ['Click handlers', 'Hover effects', 'Focus states'],
  },
  responsive: {
    label: 'Responsive',
    description: 'Mobile-friendly responsive design',
    icon: Smartphone,
    features: ['Media queries', 'Flexible layouts', 'Touch support'],
  },
  prototype: {
    label: 'Prototype',
    description: 'Full prototype with navigation',
    icon: Layers,
    features: ['Page navigation', 'State management', 'Transitions'],
  },
};

const deviceConfig = {
  desktop: { icon: Monitor, width: '100%', label: 'Desktop' },
  tablet: { icon: Tablet, width: '768px', label: 'Tablet' },
  mobile: { icon: Smartphone, width: '375px', label: 'Mobile' },
};

export default function InteractiveHTMLExport({
  variant = 'full',
  mockupName = 'My Mockup',
  onExport,
  onPreview,
  className = '',
}: InteractiveHTMLExportProps) {
  const [settings, setSettings] = useState<HTMLExportSettings>({
    preset: 'interactive',
    includeCSS: true,
    inlineStyles: false,
    minify: false,
    responsive: true,
    darkModeSupport: true,
    clickableElements: true,
    hoverEffects: true,
    animations: true,
    exportAsZip: false,
  });

  const [interactivityOptions, setInteractivityOptions] = useState<InteractivityOption[]>([
    { id: 'click', label: 'Clickable Elements', description: 'Buttons and links work', enabled: true, icon: MousePointer },
    { id: 'hover', label: 'Hover Effects', description: 'Visual feedback on hover', enabled: true, icon: Zap },
    { id: 'focus', label: 'Focus States', description: 'Keyboard navigation support', enabled: true, icon: Layers },
    { id: 'scroll', label: 'Scroll Effects', description: 'Smooth scroll behavior', enabled: false, icon: RefreshCw },
  ]);

  const [devicePreview, setDevicePreview] = useState<DevicePreview>('desktop');
  const [isExporting, setIsExporting] = useState(false);
  const [isCopied, setIsCopied] = useState(false);
  const [showAdvanced, setShowAdvanced] = useState(false);
  const [generatedCode, setGeneratedCode] = useState<string | null>(null);

  const handleExport = useCallback(async () => {
    setIsExporting(true);

    // Simulate export
    await new Promise(resolve => setTimeout(resolve, 2000));

    // Generate sample HTML
    const html = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${mockupName}</title>
  <style>
    /* Generated by MockFlow */
    * { box-sizing: border-box; }
    body { margin: 0; font-family: system-ui, sans-serif; }
    .mockup-container { max-width: 1200px; margin: 0 auto; }
    ${settings.darkModeSupport ? '@media (prefers-color-scheme: dark) { body { background: #1a1a1a; color: #fff; } }' : ''}
    ${settings.responsive ? '@media (max-width: 768px) { .mockup-container { padding: 1rem; } }' : ''}
  </style>
</head>
<body>
  <div class="mockup-container">
    <!-- Your mockup content here -->
  </div>
</body>
</html>`;

    setGeneratedCode(html);
    setIsExporting(false);
    onExport?.(settings);
  }, [settings, mockupName, onExport]);

  const handleCopyCode = useCallback(async () => {
    if (generatedCode) {
      await navigator.clipboard.writeText(generatedCode);
      setIsCopied(true);
      setTimeout(() => setIsCopied(false), 2000);
    }
  }, [generatedCode]);

  const handleInteractivityToggle = useCallback((id: string) => {
    setInteractivityOptions(prev =>
      prev.map(opt => opt.id === id ? { ...opt, enabled: !opt.enabled } : opt),
    );
  }, []);

  // Widget variant
  if (variant === 'widget') {
    return (
      <div className={`rounded-lg border border-gray-200 bg-white p-3 dark:border-gray-700 dark:bg-gray-800 ${className}`}>
        <div className="mb-2 flex items-center gap-2">
          <Code className="h-4 w-4 text-green-500" />
          <span className="text-sm font-medium text-gray-900 dark:text-white">HTML Export</span>
        </div>
        <button
          onClick={handleExport}
          className="w-full rounded bg-green-600 py-2 text-sm text-white hover:bg-green-700"
        >
          Export HTML
        </button>
      </div>
    );
  }

  // Compact variant
  if (variant === 'compact') {
    return (
      <div className={`rounded-lg border border-gray-200 bg-white p-4 dark:border-gray-700 dark:bg-gray-800 ${className}`}>
        <div className="mb-4 flex items-center justify-between">
          <div className="flex items-center gap-2">
            <Code className="h-5 w-5 text-green-500" />
            <h3 className="font-semibold text-gray-900 dark:text-white">Interactive HTML</h3>
          </div>
        </div>

        <div className="mb-4 grid grid-cols-2 gap-2">
          {(['basic', 'interactive'] as ExportPreset[]).map(preset => (
            <button
              key={preset}
              onClick={() => setSettings(prev => ({ ...prev, preset }))}
              className={`rounded-lg border p-3 text-center text-sm transition-colors ${
                settings.preset === preset
                  ? 'border-green-500 bg-green-50 text-green-700 dark:bg-green-900/30 dark:text-green-300'
                  : 'border-gray-200 hover:bg-gray-50 dark:border-gray-700 dark:hover:bg-gray-700'
              }`}
            >
              {presetConfig[preset].label}
            </button>
          ))}
        </div>

        <button
          onClick={handleExport}
          disabled={isExporting}
          className="flex w-full items-center justify-center gap-2 rounded-lg bg-green-600 py-2 text-white hover:bg-green-700 disabled:opacity-50"
        >
          {isExporting
            ? (
                <>
                  <Loader2 className="h-4 w-4 animate-spin" />
                  Generating...
                </>
              )
            : (
                <>
                  <Download className="h-4 w-4" />
                  Export HTML
                </>
              )}
        </button>
      </div>
    );
  }

  // Full variant
  return (
    <div className={`rounded-xl bg-white shadow-lg dark:bg-gray-900 ${className}`}>
      {/* Header */}
      <div className="border-b border-gray-200 p-6 dark:border-gray-700">
        <div className="flex items-center justify-between">
          <div className="flex items-center gap-3">
            <div className="flex h-12 w-12 items-center justify-center rounded-xl bg-gradient-to-br from-green-500 to-emerald-500">
              <Code className="h-6 w-6 text-white" />
            </div>
            <div>
              <h2 className="text-xl font-bold text-gray-900 dark:text-white">Interactive HTML Export</h2>
              <p className="text-sm text-gray-600 dark:text-gray-400">Export as clickable HTML prototype</p>
            </div>
          </div>
          <div className="flex items-center gap-2">
            {(['desktop', 'tablet', 'mobile'] as DevicePreview[]).map((device) => {
              const config = deviceConfig[device];
              const Icon = config.icon;
              return (
                <button
                  key={device}
                  onClick={() => {
                    setDevicePreview(device);
                    onPreview?.(device);
                  }}
                  className={`rounded-lg p-2 transition-colors ${
                    devicePreview === device
                      ? 'bg-green-100 text-green-600 dark:bg-green-900/30 dark:text-green-400'
                      : 'text-gray-400 hover:bg-gray-100 dark:hover:bg-gray-800'
                  }`}
                  title={config.label}
                >
                  <Icon className="h-5 w-5" />
                </button>
              );
            })}
          </div>
        </div>
      </div>

      <div className="grid grid-cols-2 divide-x divide-gray-200 dark:divide-gray-700">
        {/* Left: Settings */}
        <div className="space-y-6 p-6">
          {/* Preset Selection */}
          <div>
            <h3 className="mb-3 text-sm font-semibold text-gray-900 dark:text-white">Export Preset</h3>
            <div className="grid grid-cols-2 gap-3">
              {(Object.keys(presetConfig) as ExportPreset[]).map((preset) => {
                const config = presetConfig[preset];
                const Icon = config.icon;
                return (
                  <button
                    key={preset}
                    onClick={() => setSettings(prev => ({ ...prev, preset }))}
                    className={`rounded-xl border-2 p-4 text-left transition-all ${
                      settings.preset === preset
                        ? 'border-green-500 bg-green-50 dark:bg-green-900/30'
                        : 'border-gray-200 hover:border-gray-300 dark:border-gray-700 dark:hover:border-gray-600'
                    }`}
                  >
                    <Icon className={`mb-2 h-6 w-6 ${settings.preset === preset ? 'text-green-600' : 'text-gray-400'}`} />
                    <p className="font-semibold text-gray-900 dark:text-white">{config.label}</p>
                    <p className="mt-1 text-xs text-gray-500">{config.description}</p>
                  </button>
                );
              })}
            </div>
          </div>

          {/* Interactivity Options */}
          <div>
            <h3 className="mb-3 text-sm font-semibold text-gray-900 dark:text-white">Interactivity</h3>
            <div className="space-y-2">
              {interactivityOptions.map((option) => {
                const Icon = option.icon;
                return (
                  <div
                    key={option.id}
                    className={`flex items-center justify-between rounded-lg border p-3 transition-colors ${
                      option.enabled
                        ? 'border-green-200 bg-green-50 dark:border-green-800 dark:bg-green-900/20'
                        : 'border-gray-200 dark:border-gray-700'
                    }`}
                  >
                    <div className="flex items-center gap-3">
                      <Icon className={`h-5 w-5 ${option.enabled ? 'text-green-600' : 'text-gray-400'}`} />
                      <div>
                        <p className="font-medium text-gray-900 dark:text-white">{option.label}</p>
                        <p className="text-xs text-gray-500">{option.description}</p>
                      </div>
                    </div>
                    <label className="relative inline-flex cursor-pointer items-center">
                      <input
                        type="checkbox"
                        checked={option.enabled}
                        onChange={() => handleInteractivityToggle(option.id)}
                        className="peer sr-only"
                      />
                      <div className="peer h-6 w-11 rounded-full bg-gray-200 peer-checked:bg-green-600 peer-focus:ring-4 peer-focus:ring-green-300 peer-focus:outline-none after:absolute after:top-[2px] after:left-[2px] after:h-5 after:w-5 after:rounded-full after:border after:border-gray-300 after:bg-white after:transition-all after:content-[''] peer-checked:after:translate-x-full peer-checked:after:border-white dark:border-gray-600 dark:bg-gray-700 dark:peer-focus:ring-green-800" />
                    </label>
                  </div>
                );
              })}
            </div>
          </div>

          {/* Quick Options */}
          <div className="grid grid-cols-2 gap-3">
            <label className="flex cursor-pointer items-center gap-2 rounded-lg bg-gray-50 p-3 dark:bg-gray-800">
              <input
                type="checkbox"
                checked={settings.responsive}
                onChange={e => setSettings(prev => ({ ...prev, responsive: e.target.checked }))}
                className="h-4 w-4 rounded text-green-600"
              />
              <span className="text-sm text-gray-700 dark:text-gray-300">Responsive</span>
            </label>
            <label className="flex cursor-pointer items-center gap-2 rounded-lg bg-gray-50 p-3 dark:bg-gray-800">
              <input
                type="checkbox"
                checked={settings.darkModeSupport}
                onChange={e => setSettings(prev => ({ ...prev, darkModeSupport: e.target.checked }))}
                className="h-4 w-4 rounded text-green-600"
              />
              <span className="text-sm text-gray-700 dark:text-gray-300">Dark Mode</span>
            </label>
            <label className="flex cursor-pointer items-center gap-2 rounded-lg bg-gray-50 p-3 dark:bg-gray-800">
              <input
                type="checkbox"
                checked={settings.minify}
                onChange={e => setSettings(prev => ({ ...prev, minify: e.target.checked }))}
                className="h-4 w-4 rounded text-green-600"
              />
              <span className="text-sm text-gray-700 dark:text-gray-300">Minify</span>
            </label>
            <label className="flex cursor-pointer items-center gap-2 rounded-lg bg-gray-50 p-3 dark:bg-gray-800">
              <input
                type="checkbox"
                checked={settings.exportAsZip}
                onChange={e => setSettings(prev => ({ ...prev, exportAsZip: e.target.checked }))}
                className="h-4 w-4 rounded text-green-600"
              />
              <span className="text-sm text-gray-700 dark:text-gray-300">ZIP Archive</span>
            </label>
          </div>

          {/* Advanced Settings */}
          <div>
            <button
              onClick={() => setShowAdvanced(!showAdvanced)}
              className="flex items-center gap-2 text-sm font-medium text-gray-700 dark:text-gray-300"
            >
              <Settings className="h-4 w-4" />
              Advanced Options
              <ChevronDown className={`h-4 w-4 transition-transform ${showAdvanced ? 'rotate-180' : ''}`} />
            </button>

            {showAdvanced && (
              <div className="mt-4 space-y-3 rounded-lg bg-gray-50 p-4 dark:bg-gray-800">
                <label className="flex items-center gap-2">
                  <input
                    type="checkbox"
                    checked={settings.inlineStyles}
                    onChange={e => setSettings(prev => ({ ...prev, inlineStyles: e.target.checked }))}
                    className="h-4 w-4 rounded text-green-600"
                  />
                  <span className="text-sm text-gray-700 dark:text-gray-300">Inline Styles (no external CSS)</span>
                </label>
                <label className="flex items-center gap-2">
                  <input
                    type="checkbox"
                    checked={settings.animations}
                    onChange={e => setSettings(prev => ({ ...prev, animations: e.target.checked }))}
                    className="h-4 w-4 rounded text-green-600"
                  />
                  <span className="text-sm text-gray-700 dark:text-gray-300">Include CSS Animations</span>
                </label>
                <div>
                  <label className="mb-1 block text-sm text-gray-600 dark:text-gray-400">Custom CSS</label>
                  <textarea
                    value={settings.customCSS || ''}
                    onChange={e => setSettings(prev => ({ ...prev, customCSS: e.target.value }))}
                    placeholder="/* Your custom CSS */"
                    className="h-24 w-full rounded-lg border border-gray-300 bg-white px-3 py-2 font-mono text-sm dark:border-gray-600 dark:bg-gray-700"
                  />
                </div>
              </div>
            )}
          </div>
        </div>

        {/* Right: Preview & Export */}
        <div className="space-y-6 p-6">
          {/* Preview */}
          <div className="min-h-[300px] rounded-xl bg-gray-100 p-4 dark:bg-gray-800">
            <div
              className="mx-auto overflow-hidden rounded-lg bg-white shadow-lg transition-all duration-300 dark:bg-gray-900"
              style={{ maxWidth: deviceConfig[devicePreview].width }}
            >
              {/* Browser Chrome */}
              <div className="flex items-center gap-2 bg-gray-200 px-3 py-2 dark:bg-gray-700">
                <div className="flex gap-1.5">
                  <div className="h-3 w-3 rounded-full bg-red-400" />
                  <div className="h-3 w-3 rounded-full bg-yellow-400" />
                  <div className="h-3 w-3 rounded-full bg-green-400" />
                </div>
                <div className="mx-4 flex-1">
                  <div className="flex items-center gap-1 rounded bg-white px-3 py-1 text-xs text-gray-500 dark:bg-gray-600 dark:text-gray-400">
                    <Globe className="h-3 w-3" />
                    {mockupName.toLowerCase().replace(/\s+/g, '-')}
                    .html
                  </div>
                </div>
              </div>
              {/* Content */}
              <div className="p-8 text-center">
                <FileCode className="mx-auto mb-4 h-12 w-12 text-gray-300 dark:text-gray-600" />
                <p className="text-sm text-gray-500">HTML Preview</p>
                <p className="mt-1 text-xs text-gray-400">Click export to generate</p>
              </div>
            </div>
          </div>

          {/* Generated Code */}
          {generatedCode && (
            <div>
              <div className="mb-2 flex items-center justify-between">
                <h3 className="text-sm font-semibold text-gray-900 dark:text-white">Generated Code</h3>
                <button
                  onClick={handleCopyCode}
                  className="flex items-center gap-1 text-sm text-green-600 hover:text-green-700"
                >
                  {isCopied ? <Check className="h-4 w-4" /> : <Copy className="h-4 w-4" />}
                  {isCopied ? 'Copied!' : 'Copy'}
                </button>
              </div>
              <pre className="max-h-48 overflow-x-auto rounded-lg bg-gray-900 p-4 text-xs text-gray-100">
                <code>
                  {generatedCode.slice(0, 500)}
                  ...
                </code>
              </pre>
            </div>
          )}

          {/* Export Stats */}
          <div className="grid grid-cols-3 gap-4 rounded-lg bg-gray-50 p-4 dark:bg-gray-800">
            <div className="text-center">
              <p className="text-lg font-bold text-gray-900 dark:text-white">~12 KB</p>
              <p className="text-xs text-gray-500">Est. Size</p>
            </div>
            <div className="text-center">
              <p className="text-lg font-bold text-gray-900 dark:text-white">{interactivityOptions.filter(o => o.enabled).length}</p>
              <p className="text-xs text-gray-500">Interactions</p>
            </div>
            <div className="text-center">
              <p className="text-lg font-bold text-gray-900 dark:text-white">
                {settings.responsive ? '3' : '1'}
              </p>
              <p className="text-xs text-gray-500">Breakpoints</p>
            </div>
          </div>

          {/* Export Buttons */}
          <div className="space-y-3">
            <button
              onClick={handleExport}
              disabled={isExporting}
              className="flex w-full items-center justify-center gap-2 rounded-xl bg-gradient-to-r from-green-600 to-emerald-600 py-4 font-semibold text-white shadow-lg hover:from-green-700 hover:to-emerald-700 disabled:opacity-50"
            >
              {isExporting
                ? (
                    <>
                      <Loader2 className="h-5 w-5 animate-spin" />
                      Generating HTML...
                    </>
                  )
                : (
                    <>
                      <Download className="h-5 w-5" />
                      Export HTML
                      {' '}
                      {settings.exportAsZip ? 'ZIP' : 'File'}
                    </>
                  )}
            </button>

            <button
              onClick={() => window.open('about:blank', '_blank')}
              disabled={!generatedCode}
              className="flex w-full items-center justify-center gap-2 rounded-xl border border-gray-200 bg-white py-3 font-medium text-gray-700 hover:bg-gray-50 disabled:opacity-50 dark:border-gray-700 dark:bg-gray-800 dark:text-gray-300 dark:hover:bg-gray-700"
            >
              <ExternalLink className="h-4 w-4" />
              Open in New Tab
            </button>
          </div>

          {/* Info */}
          <div className="flex items-start gap-2 rounded-lg border border-blue-200 bg-blue-50 p-3 dark:border-blue-800 dark:bg-blue-900/20">
            <AlertCircle className="mt-0.5 h-5 w-5 flex-shrink-0 text-blue-600 dark:text-blue-400" />
            <p className="text-sm text-blue-800 dark:text-blue-300">
              Exported HTML is self-contained and works offline. Perfect for sharing prototypes!
            </p>
          </div>
        </div>
      </div>
    </div>
  );
}

export type { DevicePreview, ExportPreset, HTMLExportSettings, InteractiveHTMLExportProps };
